#!/usr/bin/env python3
"""Turn catalog.json into a C initializer included by pokedex.c."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "assets" / "pokedex" / "gen1" / "catalog.json"
OUT = ROOT / "main" / "pokedex_catalog.inc"
MOVE_MAX = 8
EVO_MAX = 8


def c_str(text: str) -> str:
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def main() -> int:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    lines = ["/* Generated by tools/pokedex/gen_catalog_inc.py. Do not edit. */", ""]
    for entry in data["entries"]:
        types = entry.get("types") or [""]
        type_a = types[0] if types else ""
        type_b = types[1] if len(types) > 1 else ""
        moves = (entry.get("moves") or [])[:MOVE_MAX]
        evo = (entry.get("evolution") or [])[:EVO_MAX]
        move_lv = ", ".join(str(int(m.get("level") or 0)) for m in moves) or "0"
        move_zh = ", ".join(c_str(m.get("zh") or "") for m in moves) or '""'
        evo_zh = ", ".join(c_str(n.get("zh") or "") for n in evo) or '""'
        evo_cond = ", ".join(c_str(n.get("condition") or "") for n in evo) or '""'
        stats = entry.get("stats") or {}
        lines.append("    {")
        lines.append(f"        .zh = {c_str(entry.get('zh') or '')},")
        lines.append(f"        .en = {c_str(entry.get('en') or '')},")
        lines.append(f"        .category = {c_str(entry.get('category') or '')},")
        lines.append(f"        .type_a = {c_str(type_a)},")
        lines.append(f"        .type_b = {c_str(type_b)},")
        lines.append(f"        .intro = {c_str(entry.get('intro') or '')},")
        lines.append(f"        .hp = {int(stats.get('hp') or 0)},")
        lines.append(f"        .atk = {int(stats.get('atk') or 0)},")
        lines.append(f"        .def_ = {int(stats.get('def') or 0)},")
        lines.append(f"        .spa = {int(stats.get('spa') or 0)},")
        lines.append(f"        .spd = {int(stats.get('spd') or 0)},")
        lines.append(f"        .spe = {int(stats.get('spe') or 0)},")
        lines.append(f"        .move_n = {len(moves)},")
        lines.append(f"        .move_lv = {{ {move_lv} }},")
        lines.append(f"        .move_zh = {{ {move_zh} }},")
        lines.append(f"        .evo_n = {len(evo)},")
        lines.append(f"        .evo_zh = {{ {evo_zh} }},")
        lines.append(f"        .evo_cond = {{ {evo_cond} }},")
        lines.append("    },")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(OUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
